steps:
  #Build the container image
- name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/simple_webapp', '.']
  #push the container image 
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/$PROJECT_ID/simple_webapp']
  #push the container image 
- name: 'gcr.io/cloud-builders/gke-deploy'
  args: 
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=gke.yaml
  - --image=gcr.io/$PROJECT_ID/simple_webapp
  - --location=us-central1-c
  - --cluster=cluster-1
  - --namespace=gcp-devops-prod
